// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://navaoaxmbkbbuxomkldq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdmFvYXhtYmtiYnV4b21rbGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzI4NDQsImV4cCI6MjA2NTY0ODg0NH0.pG7InPiEqXIm_UPkPkg0IgdqEG4sHovpp7Ju0jafHvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);